import React, { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import Wrapper from '../components/Wrapper'
import { Container } from '../styles/styled-components/Container'
import { DataContext } from '../store/GlobalState'
import { CartTable, CartTotal } from '../styles/styled-components/Cart'
import { Button } from '@material-ui/core'
import { createTheme, MuiThemeProvider } from '@material-ui/core/styles'
import { HiMinusCircle, HiPlusCircle } from 'react-icons/hi'
import { FaTrash } from 'react-icons/fa'
import { increase, decrease, remove } from '../store/Action'

const Cart = () => {
  const { state, dispatch } = useContext(DataContext)
  const { cart } = state

  const [total, setTotal] = useState(0)

  const [products, setProducts] = useState(cart)

  const [itemValues, setItemValues] = useState([])

  const theme = createTheme({
    palette: {
      primary: {
        light: '#9B78EB',
        main: '#8E67E8',
        dark: '#8257e6',
        contrastText: '#fff'
      }
    }
  })

  const handleCalcularTotal = event => {
    // setTotal(
    //   total + parseInt(item.price) * e.target.value
    // )
    console.log(event.target.value)
  }
  const handleIncreaseItem = (id) => {

  }

  useEffect(() => {
    setProducts(cart)
    let calc = 0
    cart.map(e => {
      calc += e.quantity * e.price
    })
    setTotal(calc)
    // setItemValues(list)
    // console.log(list)
  }, [cart])
  return (
    <MuiThemeProvider theme={theme}>
      <Wrapper>
        <Head>
          <title>Carrinho</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
          <h1>Carrinho</h1>
          {cart.length > 0 && itemValues ? (
            <div style={{ display: 'flex', justifyContent: 'space-around' }}>
              <CartTable>
                <thead>
                  <tr>
                    <th>
                      <span className="thItem">Item</span>
                    </th>
                    <th style={{ width: '100px' }}>Quantidade</th>
                    <th>
                      <p>Preço</p>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {products.map((item, index) => (
                    <tr key={index}>
                      <td>
                        <div className="productInfo">
                          <img width="50px" src={item.images[0].url} alt="" />
                          <h4 style={{ display: 'flex', alignItems: 'center' }}>
                            {item.title}
                          </h4>
                        </div>
                      </td>
                      <td className="productQtdd">
                        <center>
                          {/* <input
                            type="text"
                            name="quantity"
                            // id={}
                            defaultValue={item.quantity}
                            // value={itemValues[index]}
                            disabled
                            onChange={e => handleCalcularTotal(e)}
                          /> */}
                          <p>{item.quantity}</p>
                          <div style={{ display: 'flex', alignItems: 'center' }}>
                            <HiPlusCircle size="25px" onClick={() => dispatch(increase(cart,  item._id))}/>
                            <HiMinusCircle size="25px" onClick={() => dispatch(decrease(cart,  item._id))} />
                            <FaTrash size="20px"onClick={() => dispatch(remove(cart,  item._id))} />
                          </div>
                          {/* <a href="#" className={item._id} onClick={(e) => alert("remover produto pelo id: " + e.target.className)}>
                            Remover
                          </a> */}
                        </center>
                      </td>
                      <td>
                        <p>R${item.price}</p>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </CartTable>
              <CartTotal>
                <h4>
                  Integer vehicula et leo id volutpat. Vestibulum ante ipsum
                  primis in faucibus orci luctus et ultrices posuere cubilia
                  curae; In quam purus, blandit non neque vitae, consectetur
                  iaculis nulla. In et facilisis tellus.
                </h4>
                <h4 style={{ color: 'purple' }}>
                  TOTAL:{' '}
                  {total.toLocaleString('pt-BR', {
                    style: 'currency',
                    currency: 'BRL'
                  })}
                </h4>
                <Button
                  color="primary"
                  variant="contained"
                  // startIcon={<MdAddShoppingCart />}
                  onClick={() =>
                    dispatch({
                      type: 'NOTIFY',
                      payload: {
                        error: 'Aguarde... Estamos finalizando sua compra.'
                      }
                    })
                  }
                >
                  Finalizar compra
                </Button>
              </CartTotal>
            </div>
          ) : (
            <h4>Ops! Nenhum produto no carrinho. Confira nossos produtos =)</h4>
          )}
        </Container>
      </Wrapper>
    </MuiThemeProvider>
  )
}

export default Cart
