import React, { useState } from 'react'
import Head from 'next/head'

import { ContainerGeral } from '../styles/styled-components/ContainerGeral'
import Wrapper from '../components/Wrapper'
import { Container } from '../styles/styled-components/Container'
import ProductCard from '../components/ProductCard'
import ProductCardLis from '../components/ProductCardLis'
import styled from 'styled-components'
import { getData } from '../../utils/fetchData'

const ContainerIndex = styled(Container)`
  flex-direction: column;
`
const Home = ({products}) => {
  const [productList, setProductList] = useState(products);

  return (
    <ContainerGeral>
      <Head>
        <title>Lojinha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <ContainerIndex>
          <h1>Bem vindo a Lojinha</h1>
          <ProductCardLis>
            {productList.length === 0 ? (
              <h1>Sem produtos!</h1>
            ) : (
              productList.map((product, index) => (
                <ProductCard
                  key={index}
                  title={product.title}
                  price={product.price}
                  description={product.content}
                  content={product.content}
                  images={product.images[0].url}
                  category={product.category}
                  checked={false}
                  inStock="10"
                  sold="156"
                />
            ))
            )}
            <ProductCard
              title="Mouse Gamer"
              price={229.99}
              description="Aenean ac orci porttitor, placerat magna ut, venenatis metus. Aliquam non turpis sapien..."
              content="Aenean ac orci porttitor, placerat magna ut, venenatis metus. Aliquam non turpis sapien. Duis et nunc luctus quam bibendum vestibulum. Duis lacus enim, ultricies vitae luctus et, auctor vitae metus."
              images="https://images.tcdn.com.br/img/img_prod/699576/mouse_gamer_redragon_impact_rgb_12400dpi_m908_1069_1_20200404102045.png"
              category="eletrônicos"
              checked={false}
              inStock="10"
              sold="156"
            />
          </ProductCardLis>
        </ContainerIndex>
      </Wrapper>
    </ContainerGeral>
  )
}

export async function getServerSideProps({query}){
  const res = await getData('product');
  console.log(res);

  return {
    props: {
      products: res.products,
      result: res.result
    }
  }
}

export default Home
