import React from 'react'
import Head from 'next/head'

import { Container } from '../styles/Pages/Home'
import Wrapper from '../components/Wrapper'

 const Home: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Lojinha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <h1>Bem vindo a Lojinha</h1>
      </Wrapper>
    </Container>
  )
}
export default Home;
