import React from 'react'
import Head from 'next/head'

import Logo from  '../assets/img/logo.svg'
import { Container } from '../styles/Pages/Home'

 const Home: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Lojinha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Logo />
        <h1>Bem vindo a Lojinha</h1>
    </Container>
  )
}
export default Home;
