import Head from 'next/head';
import React from 'react';

// import { Container } from './styles';
import Wrapper from '../components/Wrapper';
import {Container} from '../styles/styled-components/Container';

const Sobre: React.FC = () => {
  return (
    <Wrapper>
      <Head>
        <title>Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1>Sobre</h1>
      </Container>
    </Wrapper>
  );
}

export default Sobre;
